[package]
name = "queryflux-access-control"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
queryflux-core = { workspace = true }
async-trait = { workspace = true }
reqwest = { workspace = true }
dashmap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
